### ISSUE TITLE
New fake news sites

### ISSUE THREAD

**Issue by ghost** [naveednajam/Little-Snitch---Rule-Groups#11]
Please add these sites as Fakenews (some are german).
Thank you.

afd.de
blog.halle-leaks.de
contra-magazin.com
crimekalender.wordpress.com
de.news-front.info
de.sputniknews.com
denken-macht-frei.info
deutsch.rt.com
deutsche-stimme.de
deutsche-wirtschafts-nachrichten.de
diepresse.com
dortmundecho.org
einwanderungskritik.de
epochtimes.de
freiezeiten.net
gloria.tv
halle-leaks.de
hartgeld.com
journalistenwatch.com
kopp-report.de
kulturstudio.info
kulturstudio.wordpress.com
michael-mannheimer.net
news-front.info
noch.info
npd-mv.de
politikstube.com
politikversagen.net
pressefreiheit24.wordpress.com
rapefugees.net
schluesselkindblog.com
sputniknews.com
theeuropean.de
truth24.net
unzensuriert.de
volksstimme.de
www.afd.de
www.contra-magazin.com
www.denken-macht-frei.info
www.dortmundecho.org
www.epochtimes.de
www.freiezeiten.net
www.journalistenwatch.com
www.npd-mv.de
www.politikversagen.net
www.rapefugees.net
www.theeuropean.de
www.truth24.net
www.unzensuriert.de
www.volksstimme.de

**Comment by naveednajam** [comment]
Thanks for providing the enhancements. it would be more appropriate to submit it to StevenBlack project following the link [https://github.com/StevenBlack/hosts#how-can-i-contribute-hosts-records](https://github.com/StevenBlack/hosts#how-can-i-contribute-hosts-records)

**Comment by naveednajam** [comment]
Hi check out the [RuleGroupsV2](https://rulegroups.com)
