### ISSUE TITLE
Provide better documentation

### ISSUE THREAD

**Issue by Tekl** [naveednajam/Little-Snitch---Rule-Groups#12]
There are a lot of files. What should I subscribe in LS to get "Unified hosts + fakenews + gambling + porn + social"?

**Comment by Tekl** [comment]
Oh sorry. I've found the combined file. I haven't realized that Github truncates the folder names. But anyway an instruction for noobs would be fine.

**Comment by naveednajam** [comment]
Hi check out the [RuleGroupsV2](https://rulegroups.com)
