### ISSUE TITLE
standalone extensions to base hosts

### ISSUE THREAD

**Issue by pilarArr** [naveednajam/Little-Snitch---Rule-Groups#13]
It would be nice if the fakenews, porn, gambling and social are also provided separate from the hosts base.

that way one can subscribe to each one separately but turn them off as needed without having to turn off all the rules.

for example I want to have the social rules subscription, but at some point I want to go to social sites without having to turn off the ads subscription.

**Comment by naveednajam** [comment]
sure I will look into it asap.

**Comment by naveednajam** [comment]
Hi check out the [RuleGroupsV2](https://rulegroups.com). I have wrote the scripts from the ground up to make the rule groups more manageable and easier to subscribe. As many sources in stevenblack hosts repo are not updating I explored few more sources and also open to suggestion.
