### ISSUE TITLE
Difference between unified_hosts_fakenews-gambling-porn-social and unified_hosts_base

### ISSUE THREAD

**Issue by mjclemente** [naveednajam/Little-Snitch---Rule-Groups#14]
Excuse my ignorance - just wondering what the difference is between unified_hosts_base and unified_hosts_fakenews-gambling-porn-social.

Thanks!

**Comment by naveednajam** [comment]
Unified_host_base consists of malware/adware/riskware and tracking related domains. This is the minimum recommend to protect ourselves. Fakenews , gambling, porn are extensions which adds extra domains/urls based on category

**Comment by mjclemente** [comment]
Ahh. Got it. Thank you - makes complete sense. Much appreciated!
