### ISSUE TITLE
superfluous rules

### ISSUE THREAD

**Issue by pgeorgan** [naveednajam/Little-Snitch---Rule-Groups#15]
You have 3 rules in stevenblack0.lsrules with the null domain:

`"remote-domains" : ""
`

Just fyi.

**Comment by naveednajam** [comment]
I will check on this. Can you tell me which file?

**Comment by pgeorgan** [comment]
[https://raw.githubusercontent.com/naveednajam/Little-Snitch---Rule-Groups/master/unified_host_f_g_p/stevenblack0.lsrules](url)

**Comment by naveednajam** [comment]
it's fixed now. can you check and update here

**Comment by pgeorgan** [comment]
Looks good now.

**Comment by pgeorgan** [comment]
Looks good now.
