### ISSUE TITLE
V2Rules-Groups: data couldn’t be read because of incorrect format

### ISSUE THREAD

**Issue by weleo** [naveednajam/Little-Snitch---Rule-Groups#17]
Little Snitch Version 4.5.1

On the [V2Rules-Groups website](https://rulegroups.com/) upon clicking the SUBSCRIBE button and being forwarded to Little Snitch, I get the following error:

"An error occurred while loading the rule group
The data couldn’t be read because it isn’t in the correct format."

<img width="532" alt="Screen Shot 2020-05-19 at 01 37 35" src="https://user-images.githubusercontent.com/57549150/82269250-5c78db80-9971-11ea-9e84-ea94bf0a7f74.png">

This is consistent for all URLs. Example:
` https://dl.rulegroups.com/index.php?origin=rulegroups&rulegroup=ads_uncheckyads.ads.lsrules`

Any ideas what might be my problem?

**Comment by naveednajam** [comment]
@weleo  fixed it.

**Comment by weleo** [comment]
Works! Thank you for creating this service.

**Comment by naveednajam** [comment]
I am glad it is useful. Help to spread the word so others can get benefit from it
