### ISSUE TITLE
Update of Sunday 7 June deleted all rules files

### ISSUE THREAD

**Issue by PierrickGT** [naveednajam/Little-Snitch---Rule-Groups#18]
Hi,
I guess there was a bug cause the update of Sunday 7 June, deleted all rules files.
https://github.com/naveednajam/Little-Snitch---Rule-Groups/commit/97119706e5029b2ba9ed2e8cd04dc3eadc12ce33

Maybe this is due to the update of the script to Python version 3?
https://github.com/naveednajam/Little-Snitch---Rule-Groups/commit/2d171b14f93398528fea82f2195d13de8bb130b0

**Comment by naveednajam** [comment]
I forgot to update my script which push the updated rule groups to github. Just fixed it. all files will be back in few minutes. by the way I will suggest you to check out [Rule-GroupsV2](https://rulegroups.com)
