### ISSUE TITLE
unified_hosts_base blocks Dropbox

### ISSUE THREAD

**Issue by gavinhughes** [naveednajam/Little-Snitch---Rule-Groups#19]
I use only the rules in unified_hosts_base.  This blocks Dropbox syncing.  Is there a simple fix?

**Comment by naveednajam** [comment]
Check which rule is blocking dropbox updates and disable it manually

**Comment by gavinhughes** [comment]
I tried to do this but the disable feature is itself disabled on protected rules.  There appears to be no way to disable or delete the rule.

**Comment by naveednajam** [comment]
it should not be protected, any  rule you want to disable,  just uncheck. any screenshots will be helpful if you still unable to disable the rules

**Comment by gavinhughes** [comment]
Here's the screenshot.  I'm unable to disable or delete any of the rules in unified_hosts_base. Does this have to do with the fact that I'm subscribed?

<img width="1280" alt="Screen Shot 2020-11-09 at 8 27 34 AM" src="https://user-images.githubusercontent.com/10154/98549847-59e4a800-2269-11eb-9c93-0a2867a0b24b.png">

**Comment by dvcrn** [comment]
@gavinhughes Yeah, don't edit the rule. Just uncheck the little checkbox next to it to disable it

**Comment by gavinhughes** [comment]
@dvcrn The checkboxes are also disabled, same as rule editing:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/10154/99738243-0a3b8300-2a98-11eb-9c96-4a6c4b34f626.png">

**Comment by dvcrn** [comment]
> @dvcrn The checkboxes are also disabled, same as rule editing:
> 
> 
> 
> <img width="851" alt="image" src="https://user-images.githubusercontent.com/10154/99738243-0a3b8300-2a98-11eb-9c96-4a6c4b34f626.png">
> 
> 

Open little snitch settings and enable global rule editing. That should enable the checkbox!

**Comment by gavinhughes** [comment]
Solved. The Dropbox issue was due to other rules I had created. Not related to unified_hosts_base.
