### ISSUE TITLE
An error occurred while loading the rule group

### ISSUE THREAD

**Issue by ModeConfusion** [naveednajam/Little-Snitch---Rule-Groups#20]
Error Detail "The data couldn’t be read because it isn’t in the correct format."

Subscribing to [ https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_social/sb_unified_hosts_social.lsrules ] just one example. 

Little Snitch 4.6 on Catalina

**Comment by naveednajam** [comment]
Try https://rulegroups.com

**Comment by naveednajam** [comment]
> https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_social/sb_unified_hosts_social.lsrules

you need to point to raw file url [unified_hosts_social](https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_social/sb_unified_hosts_social.lsrules?raw=true) however if will be much better if you access subscribe via rulegroups.com which is advanced version of this.
