### ISSUE TITLE
Little Snitch got slower 

### ISSUE THREAD

**Issue by georgysavva** [naveednajam/Little-Snitch---Rule-Groups#21]
Hi. I subscribed to this rule group: https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_base/sb_unified_hosts_base.lsrules

After that Little Snitch (LS) got significantly slower, every action that I do in the configuration panel takes a lot of processing time. 
Is it supposed to be like that or I am doing something wrong? Thanks!

**Comment by naveednajam** [comment]
This expected and completely normal behavior

**Comment by georgysavva** [comment]
Okay, thanks!
