### ISSUE TITLE
Request - Automatic Upload after running the script

### ISSUE THREAD

**Issue by Madd33n** [naveednajam/Little-Snitch---Rule-Groups#4]
Hi, 
i cant open a new request, so I'll describe it here. Sorry, but i dont know any other way :)

Is it possible to add a feature that allows me to upload the splitted files to my webspace automatically?
It would be very useful because people can automate the whole process with "Automator" simply running the script on the client. 
- Loading new hosts-file via stevenblack (done via your script)
- Splitting the file for matching LittleSnitch import rules (done via your script)
- Uploading the files on a choosen webspace (request)
- Keep LS-rules update automatically with the "automatic update feature" from LittleSnitch 

Hope you can understand my request.

**Comment by naveednajam** [comment]
selecting a specific webspace might not be very flexible for everyone.  More effective way is to copy this folder to local cloud drive like google drive or drop box then add the shared url from there to little snitch.
What I am planning to do is to setup this repo on my server to update the rules every week and sync with git hub.  so people can directly sync from here. if anyone has better idea is more than welcome

**Comment by Madd33n** [comment]
Nice idea with the cloud share...not sure why I don't had this  :-)

 I'll try it.

Your plan to update the list by yourself is also a good idea. But to match all the people's need you have to offer multiple repos because some people don't want the list you choose ( fakenews only, social only and so on) 

Keep on - nice work!

**Comment by Madd33n** [comment]
Hi, ok - here`s what i get so far.

1) put the folder (including subfolder unified_host_f_g_p) to the dropbox
2) share the folder
3) Set up an shell script via Automator. 
4) Simple processing your script as an app 
5) adding it to the login (autostart) items of my user. 
So the automation is finished. 

But i struggle with the save destination of your script. 
As soon as i moved it to the dropbox and execute it, it wont save the files in the subfolder /unified_host_f_g_p
It stores the files in /users/myusername

This behavior is new, because when i execute your script in my downloads-folder, it has store the files in the subfolder /unified_host_f_g_p and not in my user directory. 

Any ideas how to save the files in the correct folder? 
Maybe i have to edit my shell-script? 
Actually its just: "python /users/username/dropbox/LittleSnitchRules/stevenblack_unified_hosts_v1.1.py"

Thanks in advance.

UPDATE: Dropbox will not work. Not sure why, but when adding the file LS keeps telling that the file has the wrong format. Uploading the same file to a normal webspace works fine... seems to be a dropbox problem.

**Comment by naveednajam** [comment]
You should navigate to the directory where you want to create "unified_host_f_g_p" directory. e.g do something like this
```
cd /users/username/dropbox/LittleSnitchRules/
python stevenblack_unified_hosts_V1.1.py 
```
it will give you desired results. Recently I have many issues using dropbox so I stop using it. However google drive is more reliable.

**Comment by naveednajam** [comment]
> Your plan to update the list by yourself is also a good idea. But to match all the people's need you have to offer multiple repos because some people don't want the list you choose ( fakenews only, social only and so on)
> 
You are right it is easily achievable as I just need to change the url and create folders for each category in a similar way as stevenblack repo.

**Comment by naveednajam** [comment]
I modified and updated the script to v1.2 which will create rules for all categories in similar way as stevenblack host files are categorised. I will still maintain the old folder for other people who has already subscribed to that url and keep it update. Now these files will be updated automatically on weekly bases.I will close this request now.

**Comment by Madd33n** [comment]
EPIC! Thanks for the fast solution! Have a nice day.
