### ISSUE TITLE
Too heavy for Little Snitch / Wrong logic

### ISSUE THREAD

**Issue by JackM-521** [naveednajam/Little-Snitch---Rule-Groups#5]
The number of records is excessive for Little Snitch (LS)and It needs a lot of CPU time on every connection to check the list.

The logic is wrong for LS. It's ok when using host files but must be consolidated for LS.

For example there is no reason to have 7 records:
a.monetate.net
b.monetate.net
...
se.monetate.net 

when only one (the domain: monetate.net) is enough and future proof.

**Comment by JackM-521** [comment]
For example with some processing in a spreadsheet, the 42,034 records of Unified hosts + fakenews + gambling has become 21,678 quickly keeping only 2nd level domains and the number can go down if I drop some 1st level domains like .ru...

**Comment by naveednajam** [comment]
First of all it is not an issue, it is new feature suggestion. There are few issues ,it is not good idea to block the root domain or even worse to block the whole tld.(which I don't think little snitch support for now). it is not necessary that the whole domain is malicious or serving ads. So I disagree with your idea.as it will break many working websites. If you really think it is possible to consolidate some of the sub domains then you better suggest to stevenblack host list to do the same as I am not the maintainer of the block lists.  Still if you believe it is good to consolidate, you are more than welcome to create a branch to test this out.
