### ISSUE TITLE
No 10.000 rules limit anymore

### ISSUE THREAD

**Issue by gemmmai** [naveednajam/Little-Snitch---Rule-Groups#7]
It's not necessary to split up the rules for Little Snitch anymore. You can pack all 60.000 (and even a lot more) of them conveniently in one file.

**Comment by naveednajam** [comment]
can you provide a reference for maximum limit?
At the time of writing this script max limit per rule group was 10,000.

**Comment by gemmmai** [comment]
Actually, it's introduced in [nightly 4.3 (5222)](https://obdev.at/products/littlesnitch/download-nightly.html) and hides behind this:

> Increased the maximum number of server names allowed in a rule group.

The lates nightly (5256) works quite well with around 100.000 rules on my Air mid 2011 with 4GB ram, where I am subscribed to your combined list in one file (roughly 60.000 rules).

Possibly you might want to wait until it's properly released, but it would be a great improvement to have one subscription instead of six.. so you could already add it with a warning to only use it with the latest nightly.

**Comment by naveednajam** [comment]
Thanks for sharing your experience and update. it's great the there are huge improvement are coming to handling large number of rule in LS with better memory and cpu management. 
I will wait until 4.3 is available as stable release. then I will update the script to V1.3 for single lsrule file.

**Comment by kaznovac** [comment]
4.3 is out and they claim to support up to 200_000 rules
https://www.obdev.at/products/littlesnitch/releasenotes.html#5246-other

**Comment by naveednajam** [comment]
I have updated the script to V1.3 which will generate single file for each group rule. However I notice that loading the rules will single files still cause performance issue with Little snitch rules manager.  I still feel adding multiple files with 10,000 rule limit is better. Any feed back is appreciated. Also any suggestion are most welcome.

**Comment by josh1703658784** [comment]
@naveednajam It would be nice to keep both versions (single file and multiple files). I haven't noticed any new performance issues with Little Snitch Configuration when adding the new single file myself (coming from the previous multi-file solution).

It can be a little laggy but that was a problem long before I subscribed to this.

**Comment by naveednajam** [comment]
Agree,  I will continue to update both version multi file and single file. both will update on weekly schedule

**Comment by naveednajam** [comment]
@joshuaks @kaznovac @gemmmai  Hi check out the [RuleGroupsV2](https://rulegroups.com). I have. I wrote the scripts from the ground up  to make the rule groups more manageable and easier to subscribe. As many sources in stevenblack hosts repo are not updating I explored few more sources and also open to suggestion.
