### ISSUE TITLE
Little snitch 4.3 will give error on subscription 

### ISSUE THREAD

**Issue by olygoelements** [naveednajam/Little-Snitch---Rule-Groups#9]
An error occured while loading the rule group The data couldn’t be read because it isn’t in the correct format.
with this link: 
https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_host_f_g_p/stevenblack0.lsrules
https://github.com/naveednajam/Little-Snitch---Rule-Groups/blob/master/unified_hosts_base/stevenblack0.lsrules

**Comment by naveednajam** [comment]
user URL to raw file.
https://raw.githubusercontent.com/naveednajam/Little-Snitch---Rule-Groups/master/unified_hosts_base/stevenblack0.lsrules
